Parse array conditions
Ecomailcz/ChimpDrill pull request #1
Opened 2021-07-29 11:12 UTC by michaelbranny

https://ecomail.atlassian.net/browse/ECOMAIL-1904

2021-07-29 12:06 UTC, pekral requested changes
testy?

2021-08-02 09:07 UTC, mareshyn commented
Testy tam jsou, muzem to mergnout? @pekral

2021-08-02 11:16 UTC, pekral approved these changes

2021-08-02 11:16 UTC, pekral commented
jo.

2021-08-03 07:11 UTC, merged